boudicca:
    collector:
        #eventdb-url: http://localhost:8081
        #enricher-url=http://localhost:8085
        #enricher-url=https://enricher.boudicca.events
        ingest-auth: ingest:ingest
        webui:
            enabled: true
            port: ${server.port}
