server:
    port: 8083

spring:
    main:
        web-application-type: servlet

boudicca:
    collector:
        webui:
            enabled: true
            timeZoneId: Europe/Vienna
            port: ${server.port}
